import type { Location } from '@/types';

export const LOCATIONS: Location[] = [
  {
    slug: 'kukatpally',
    name: 'Kukatpally',
    fullName: 'Kukatpally, Hyderabad',
    metaTitle: 'Safety Nets Installation in Kukatpally, Hyderabad | Best Price',
    metaDescription: 'Looking for safety nets in Kukatpally, Hyderabad? Apparao Safety Nets offers same-day balcony, pigeon, & kids safety net installation. Free quote!',
    pincode: '500072',
    landmarks: ['Nexus Hyderabad Mall', 'Kukatpally Metro Station', 'JNTU Hyderabad'],
    popularApartments: ['Lodha Bellezza', 'Rainbow Vistas Rock Garden', 'Incor One City', 'L&T Elation'],
  },
  {
    slug: 'madhapur',
    name: 'Madhapur',
    fullName: 'Madhapur, Hyderabad',
    metaTitle: 'Safety Nets in Madhapur, Hyderabad | Pigeon & Balcony Nets',
    metaDescription: 'Premium safety nets in Madhapur, Hyderabad. Balcony nets, anti-pigeon nets, invisible grills. SS316 quality cables. Free site measurements today.',
    pincode: '500081',
    landmarks: ['Inorbit Mall', 'Shilparamam', 'Cyber Towers', 'Madhapur Metro Station'],
    popularApartments: ['My Home Abhra', 'Aparna CyberZon', 'Cybercity Rainbow Vistas', 'Fresh Living Apartments'],
  },
  {
    slug: 'gachibowli',
    name: 'Gachibowli',
    fullName: 'Gachibowli, Hyderabad',
    metaTitle: 'Safety Nets Installation in Gachibowli | Same Day Service',
    metaDescription: 'Trusted safety net services in Gachibowli, Hyderabad. Balcony safety nets, bird protection, children safety nets. 3-5 year warranty. Call now!',
    pincode: '500032',
    landmarks: ['Gachibowli Stadium', 'DLF Cyber City', 'IIIT Hyderabad', 'IKEA'],
    popularApartments: ['Prestige High Fields', 'My Home Avatar', 'Aparna Sarovar', 'Rajapushpa Atria'],
  },
  {
    slug: 'kondapur',
    name: 'Kondapur',
    fullName: 'Kondapur, Hyderabad',
    metaTitle: 'Safety Nets in Kondapur, Hyderabad | Balcony & Bird Nets',
    metaDescription: 'Affordable safety net installation in Kondapur, Hyderabad. Best rates for balcony nets, bird control, & balcony invisible grills. Same day setup.',
    pincode: '500084',
    landmarks: ['Botanical Garden', 'Sarat City Capital Mall', 'Kondapur RTO Office'],
    popularApartments: ['My Home Mangala', 'Aparna Serene Park', 'SMR Vinay Iconia', 'Lanco Hills'],
  },
  {
    slug: 'miyapur',
    name: 'Miyapur',
    fullName: 'Miyapur, Hyderabad',
    metaTitle: 'Balcony Safety Nets in Miyapur, Hyderabad | Best Rates',
    metaDescription: 'Fast safety net installations in Miyapur, Hyderabad. Balcony safety nets, anti-bird pigeon nets, ceiling cloth hangers. Call +91-9876543210.',
    pincode: '500049',
    landmarks: ['Miyapur Metro Depot', 'Miyapur Allwyn X Roads', 'Talkie Town'],
    popularApartments: ['SMR Vinay City', 'Aparna County', 'Mayuri Nagar Apartments', 'Janapriya Nile Valley'],
  },
  {
    slug: 'chandanagar',
    name: 'Chandanagar',
    fullName: 'Chandanagar, Hyderabad',
    metaTitle: 'Safety Nets Installation in Chandanagar | Free Measurement',
    metaDescription: 'Secure your home in Chandanagar, Hyderabad with premium safety nets. Balcony nets, pigeon nets, staircase nets. High strength HDPE nets.',
    pincode: '500050',
    landmarks: ['Chandanagar Railway Station', 'GSM Mall', 'Gangaram Peddamma Temple'],
    popularApartments: ['Aparna HillPark Lake Breeze', 'Aparna Cyber Life', 'Vertex Sadguru', 'Aurobindo Regent'],
  },
  {
    slug: 'kphb-colony',
    name: 'KPHB Colony',
    fullName: 'KPHB Colony, Hyderabad',
    metaTitle: 'Safety Nets in KPHB Colony, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Get premium safety net services in KPHB Colony, Hyderabad. Balcony nets, pigeon control nets, invisible grills. Fast site visits & free quotes.',
    pincode: '500072',
    landmarks: ['KPHB Phase 1 to 9', 'Forum Sujana Mall', 'KP Metro Station'],
    popularApartments: ['Jalavayu Vihar', 'Praveen\'s Luxuria', 'Lansum Etania', 'Vasavi GP Trends'],
  },
  {
    slug: 'manikonda',
    name: 'Manikonda',
    fullName: 'Manikonda, Hyderabad',
    metaTitle: 'Safety Nets Installation in Manikonda | Balcony & Bird Nets',
    metaDescription: 'Same-day safety net installation in Manikonda, Hyderabad. Specialized children safety nets, balcony nets, invisible window grills. High quality HDPE.',
    pincode: '500089',
    landmarks: ['Lanco Hills IT Park', 'Manikonda Jagir', 'Khajaguda Hills'],
    popularApartments: ['Lanco Hills Apartments', 'Aparna One', 'Anuhar Fountain Head', 'Puppalaguda Heights'],
  },
  {
    slug: 'narsingi',
    name: 'Narsingi',
    fullName: 'Narsingi, Hyderabad',
    metaTitle: 'Safety Nets in Narsingi, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Secure your balconies and windows in Narsingi, Hyderabad. Invisible grills, balcony safety nets, pigeon protection nets. Heavy-duty SS316 wires.',
    pincode: '500075',
    landmarks: ['Narsingi ORR Exit', 'CBIT Hyderabad', 'Kokapet Lake'],
    popularApartments: ['NCC Urban One', 'My Home Krishe', 'Aparna Western Meadows', 'Vasavi Lake City'],
  },
  {
    slug: 'kokapet',
    name: 'Kokapet',
    fullName: 'Kokapet, Hyderabad',
    metaTitle: 'Safety Nets Installation in Kokapet, Hyderabad | SS316 Grills',
    metaDescription: 'High-quality safety nets and balcony invisible grills in Kokapet, Hyderabad. Free site measurements. Best prices for high-rise apartment safety.',
    pincode: '500075',
    landmarks: ['Kokapet SEZ', 'Gandipet Lake View', 'Rockwell International School'],
    popularApartments: ['Rajapushpa Regalia', 'My Home Tarkshya', 'Aparna Sarovar Zenith', 'Prestige Tranquil'],
  },
  {
    slug: 'financial-district',
    name: 'Financial District',
    fullName: 'Financial District, Hyderabad',
    metaTitle: 'Safety Nets in Financial District, Hyderabad | Balcony Safety',
    metaDescription: 'Premium safety nets & invisible grills in Financial District, Hyderabad. Expert installations for IT professionals & high-rise apartments.',
    pincode: '500032',
    landmarks: ['Wipro Circle', 'Waverock SEZ', 'ICICI Towers', 'Continental Hospital'],
    popularApartments: ['Tanishq Heights', 'Mantri Celestia', 'Prestige High Fields', 'Golf Edge Apartments'],
  },
  {
    slug: 'jubilee-hills',
    name: 'Jubilee Hills',
    fullName: 'Jubilee Hills, Hyderabad',
    metaTitle: 'Premium Safety Nets Installation in Jubilee Hills, Hyderabad',
    metaDescription: 'Get top-tier safety net services in Jubilee Hills. Balcony safety nets, anti-bird netting, window invisible grills. Professional, customized fittings.',
    pincode: '500033',
    landmarks: ['KBR National Park', 'Apollo Hospital Jubilee Hills', 'Jubilee Hills Checkpost'],
    popularApartments: ['Jubilee Hills Enclave', 'Mrugavani Residency', 'Salarpuria Sattva Magnolia', 'DSR Inspire'],
  },
  {
    slug: 'banjara-hills',
    name: 'Banjara Hills',
    fullName: 'Banjara Hills, Hyderabad',
    metaTitle: 'Safety Nets in Banjara Hills, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Residential & commercial safety nets in Banjara Hills, Hyderabad. Pigeon protection nets, staircase safety nets, ceiling cloth hangers. Call today.',
    pincode: '500034',
    landmarks: ['GVK One Mall', 'Taj Krishna', 'Basavatarakam Cancer Hospital'],
    popularApartments: ['Banjara Hills Heights', 'Aparna Crest', 'Lumbini Jewel', 'Sujana Residency'],
  },
  {
    slug: 'film-nagar',
    name: 'Film Nagar',
    fullName: 'Film Nagar, Hyderabad',
    metaTitle: 'Safety Nets Installation in Film Nagar, Hyderabad | Best Price',
    metaDescription: 'Trusted safety net service providers in Film Nagar, Hyderabad. Balcony nets, pigeon control, kids safety, sports practice nets. Free measurements.',
    pincode: '500096',
    landmarks: ['Film Nagar Cultural Center', 'Apollo Cradle', 'Whisper Valley'],
    popularApartments: ['Whisper Valley Villas', 'Film Nagar Enclave', 'Aditya Empress Towers', 'Vazhraa Pranam'],
  },
  {
    slug: 'begumpet',
    name: 'Begumpet',
    fullName: 'Begumpet, Hyderabad',
    metaTitle: 'Safety Nets in Begumpet, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Same-day balcony safety nets and pigeon control installation in Begumpet, Hyderabad. Fast response and certified durable materials.',
    pincode: '500016',
    landmarks: ['Begumpet Airport', 'Prakash Nagar Metro', 'Lifestyle Store'],
    popularApartments: ['Manbhum Solitaire', 'Mayfair Apartments', 'Lumbini Enclave', 'Royal Pavilion'],
  },
  {
    slug: 'ameerpet',
    name: 'Ameerpet',
    fullName: 'Ameerpet, Hyderabad',
    metaTitle: 'Safety Nets Installation in Ameerpet, Hyderabad | Same Day',
    metaDescription: 'Premium safety net services in Ameerpet, Hyderabad. Balcony nets, pigeon protection, window invisible grills. Best price guarantee. Call now!',
    pincode: '500016',
    landmarks: ['Ameerpet Metro Junction', 'Sarathi Studios', 'Satyam Theatre'],
    popularApartments: ['Janapriya Utopia', 'Aditya Elite', 'Sri Sai Anurag', 'Divya Shakthi Apartments'],
  },
  {
    slug: 'sr-nagar',
    name: 'SR Nagar',
    fullName: 'SR Nagar, Hyderabad',
    metaTitle: 'Safety Nets in SR Nagar, Hyderabad | Balcony & Bird Nets',
    metaDescription: 'Professional safety net installation in SR Nagar, Hyderabad. Balcony safety nets, anti-pigeon nets, children safety nets. Fast site inspections.',
    pincode: '500038',
    landmarks: ['SR Nagar Metro Station', 'Sanjeevaiah Park', 'Umesh Chandra Statue'],
    popularApartments: ['Vengal Rao Nagar Residency', 'Model Colony Apartments', 'SRK Solitaire'],
  },
  {
    slug: 'secunderabad',
    name: 'Secunderabad',
    fullName: 'Secunderabad, Telangana',
    metaTitle: 'Safety Nets Installation in Secunderabad | All Net Types',
    metaDescription: 'Best safety nets in Secunderabad. Balcony nets, pigeon control nets, invisible grills, ceiling cloth drying hangers. Free quotation visit today.',
    pincode: '500003',
    landmarks: ['Secunderabad Railway Station', 'Clock Tower', 'Karkhana Police Station', 'Paradox Mall'],
    popularApartments: ['Diamond Point Apartments', 'Mytri Heights', 'Regimental Bazaar Flats', 'APHB Flats'],
  },
  {
    slug: 'kompally',
    name: 'Kompally',
    fullName: 'Kompally, Hyderabad',
    metaTitle: 'Safety Nets in Kompally, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Looking for safety nets in Kompally, Hyderabad? We install top quality balcony safety nets, pigeon nets, coconut tree nets, and staircase nets. Same day.',
    pincode: '500100',
    landmarks: ['Kompally D-Mart', 'Runway 9', 'Kala Mandir Kompally'],
    popularApartments: ['Aparna Kanopy Marigold', 'Aparna Kanopy Tulip', 'Modi Emerald Heights', 'Srinivasa Heights'],
  },
  {
    slug: 'alwal',
    name: 'Alwal',
    fullName: 'Alwal, Hyderabad',
    metaTitle: 'Safety Nets Installation in Alwal, Hyderabad | Free Measurement',
    metaDescription: 'Fast, secure safety net installation in Alwal, Hyderabad. Balcony nets, pigeon nets, children safety nets. Certified high quality materials.',
    pincode: '500010',
    landmarks: ['Alwal Rythu Bazar', 'Loyola Academy Alwal', 'Father Balaiah Nagar'],
    popularApartments: ['Sree Hemadurga Residency', 'Alwal Greens', 'Janapriya Nile Valley', 'VBR Park'],
  },
  {
    slug: 'dilsukhnagar',
    name: 'Dilsukhnagar',
    fullName: 'Dilsukhnagar, Hyderabad',
    metaTitle: 'Safety Nets in Dilsukhnagar, Hyderabad | Balcony & Bird Nets',
    metaDescription: 'Top-rated safety net installation in Dilsukhnagar, Hyderabad. Pigeon nets, kids balcony nets, ceiling cloth hangers. 3-5 years warranty. Call now!',
    pincode: '500060',
    landmarks: ['Dilsukhnagar Metro Station', 'Sai Baba Temple Dilsukhnagar', 'P&T Colony'],
    popularApartments: ['Janapriya Sai Enclave', 'Dilsukhnagar Heights', 'Vasavi Nagar Apartments', 'Sree Mansion'],
  },
  {
    slug: 'lb-nagar',
    name: 'LB Nagar',
    fullName: 'LB Nagar, Hyderabad',
    metaTitle: 'Safety Nets Installation in LB Nagar, Hyderabad | Best Prices',
    metaDescription: 'Same-day safety net services in LB Nagar, Hyderabad. Balcony nets, pigeon nets, staircase safety nets, ceiling hangers. Call +91-9876543210.',
    pincode: '500074',
    landmarks: ['LB Nagar Metro Station', 'LB Nagar Circle', 'Kamineni Hospital'],
    popularApartments: ['Kakatiya Nagar Flats', 'Vasavi Metropolis', 'Green Homes LB Nagar', 'Srinivasa Residency'],
  },
  {
    slug: 'nagole',
    name: 'Nagole',
    fullName: 'Nagole, Hyderabad',
    metaTitle: 'Safety Nets in Nagole, Hyderabad | Balcony & Pigeon Nets',
    metaDescription: 'Secure your balconies and windows in Nagole, Hyderabad. Anti-bird netting, children safety nets, invisible grills. Free measurements, call us.',
    pincode: '500068',
    landmarks: ['Nagole Metro Station', 'Nagole RTO Office', 'Musi River Bridge'],
    popularApartments: ['Nagole Heights', 'Sree Sai Residency', 'Gouthami Nagar Apartments', 'APHB Colony'],
  },
  {
    slug: 'uppal',
    name: 'Uppal',
    fullName: 'Uppal, Hyderabad',
    metaTitle: 'Safety Nets Installation in Uppal, Hyderabad | Same Day',
    metaDescription: 'Affordable, secure safety net installation in Uppal, Hyderabad. Balcony safety nets, anti-bird pigeon nets. Heavy strength HDPE. Call today.',
    pincode: '500039',
    landmarks: ['Uppal Cricket Stadium', 'Uppal Metro Station', 'Little Flower School'],
    popularApartments: ['Uppal Heights', 'Aparna Cyber Heights', 'Navya Elite Apartments', 'Sri Sai Nilayam'],
  },
  {
    slug: 'tarnaka',
    name: 'Tarnaka',
    fullName: 'Tarnaka, Hyderabad',
    metaTitle: 'Safety Nets in Tarnaka, Hyderabad | Balcony & Bird Nets',
    metaDescription: 'Get high-tensile safety nets installed in Tarnaka, Hyderabad. Balcony nets, pigeon protection nets, ceiling cloth hangers. Free measuring visit.',
    pincode: '500007',
    landmarks: ['Tarnaka Metro Station', 'Osmania University Tarnaka Gate', 'NIN Hyderabad'],
    popularApartments: ['Lalitha Nagar Residency', 'Tarnaka Heights', 'Vijay Towers Tarnaka', 'Secunderabad Enclave'],
  },
  {
    slug: 'habsiguda',
    name: 'Habsiguda',
    fullName: 'Habsiguda, Hyderabad',
    metaTitle: 'Safety Nets Installation in Habsiguda, Hyderabad | Best Prices',
    metaDescription: 'Professional safety net services in Habsiguda, Hyderabad. Balcony nets, pigeon nets, staircase safety nets, ceiling drying hangers. Same day setup.',
    pincode: '500007',
    landmarks: ['Habsiguda Metro Station', 'Kakatiya Nagar Alerters', 'Street No 8 Habsiguda'],
    popularApartments: ['Habsiguda Heights', 'Gouthami Enclave', 'Kakatiya Nagar Apartments', 'Aravind Nagar Residency'],
  },
];

export function getLocationBySlug(slug: string): Location | undefined {
  return LOCATIONS.find((l) => l.slug === slug);
}
